version: 2
updates:
  # Maintain Node packages in the project root
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Maintain Node packages in the hardhat contracts directory
  - package-ecosystem: "npm"
    directory: "/contracts"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Maintain GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
